/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.11 Sat Jan  4 15:52:07 2025.
 */

#include "Srv.h"

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int ctrl_ems_0x201_unpack(
    struct ctrl_ems_0x201_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t motor_tor_iq_ki;
    uint32_t motor_tor_iq_kp;

    if (size < 8u) {
        return (-EINVAL);
    }

    motor_tor_iq_kp = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    motor_tor_iq_kp |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    motor_tor_iq_kp |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    motor_tor_iq_kp |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->motor_tor_iq_kp, &motor_tor_iq_kp, sizeof(dst_p->motor_tor_iq_kp));
    motor_tor_iq_ki = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    motor_tor_iq_ki |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    motor_tor_iq_ki |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    motor_tor_iq_ki |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->motor_tor_iq_ki, &motor_tor_iq_ki, sizeof(dst_p->motor_tor_iq_ki));

    return (0);
}

int ctrl_ems_0x201_init(struct ctrl_ems_0x201_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ctrl_ems_0x201_t));

    return 0;
}

double ctrl_ems_0x201_motor_tor_iq_kp_decode(float value)
{
    return ((double)value);
}

bool ctrl_ems_0x201_motor_tor_iq_kp_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

double ctrl_ems_0x201_motor_tor_iq_ki_decode(float value)
{
    return ((double)value);
}

bool ctrl_ems_0x201_motor_tor_iq_ki_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

int ctrl_ems_0x200_unpack(
    struct ctrl_ems_0x200_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t motor_tor_id_ki;
    uint32_t motor_tor_id_kp;

    if (size < 8u) {
        return (-EINVAL);
    }

    motor_tor_id_kp = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    motor_tor_id_kp |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    motor_tor_id_kp |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    motor_tor_id_kp |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    memcpy(&dst_p->motor_tor_id_kp, &motor_tor_id_kp, sizeof(dst_p->motor_tor_id_kp));
    motor_tor_id_ki = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    motor_tor_id_ki |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    motor_tor_id_ki |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    motor_tor_id_ki |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    memcpy(&dst_p->motor_tor_id_ki, &motor_tor_id_ki, sizeof(dst_p->motor_tor_id_ki));

    return (0);
}

int ctrl_ems_0x200_init(struct ctrl_ems_0x200_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ctrl_ems_0x200_t));

    return 0;
}

double ctrl_ems_0x200_motor_tor_id_kp_decode(float value)
{
    return ((double)value);
}

bool ctrl_ems_0x200_motor_tor_id_kp_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

double ctrl_ems_0x200_motor_tor_id_ki_decode(float value)
{
    return ((double)value);
}

bool ctrl_ems_0x200_motor_tor_id_ki_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

int ctrl_ems_0x180_pack(
    uint8_t *dst_p,
    const struct ctrl_ems_0x180_t *src_p,
    size_t size)
{
    uint32_t motor_e_angle;
    uint32_t motor_m_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&motor_m_angle, &src_p->motor_m_angle, sizeof(motor_m_angle));
    dst_p[0] |= pack_left_shift_u32(motor_m_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(motor_m_angle, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(motor_m_angle, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(motor_m_angle, 24u, 0xffu);
    memcpy(&motor_e_angle, &src_p->motor_e_angle, sizeof(motor_e_angle));
    dst_p[4] |= pack_left_shift_u32(motor_e_angle, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(motor_e_angle, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(motor_e_angle, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(motor_e_angle, 24u, 0xffu);

    return (8);
}

int ctrl_ems_0x180_init(struct ctrl_ems_0x180_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ctrl_ems_0x180_t));

    return 0;
}

float ctrl_ems_0x180_motor_m_angle_encode(double value)
{
    return (float)(value);
}

bool ctrl_ems_0x180_motor_m_angle_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

float ctrl_ems_0x180_motor_e_angle_encode(double value)
{
    return (float)(value);
}

bool ctrl_ems_0x180_motor_e_angle_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}
